const LANDING_BG_RING_MIN_SPEED = {
	LARGE: 10,
	MIDDLE: 16,
	SMALL: 20,
} as const;

const LANDING_BG_RING_SIZE = {
	LARGE: 959,
	MIDDLE: 293,
	SMALL: 166,
} as const;

const LANDING_BG_RING_SPEED_SCALE = {
	LARGE: 0.55,
	MIDDLE: 1,
	SMALL: 1.35,
} as const;

const LANDING_BG_PHYSICS = {
	DAMPING: 0.985,
	MARGIN: 0.2,
	MAX_SPEED: 220,
	SPEED_MULTIPLIER: 2,
} as const;

const LANDING_BG_COLLISION = {
	MAX_OVERLAP_FRACTION: 0.15,
	OVERLAP_EPSILON: 0.5,
} as const;

const LANDING_BG_INIT = {
	INITIAL_SPEED_HALF: 10,
	INITIAL_SPEED_RANGE: 20,
	RINGS_PER_SIZE: 3,
} as const;

const LANDING_BG_NUMERIC = {
	HALF: 2,
	MS_IN_SECOND: 1000,
	ONE: 1,
	SIDES_COUNT: 4,
	TWO: 2,
	UINT32_ARRAY_LENGTH: 1,
	UINT32_MAX: 4_294_967_296,
	ZERO: 0,
} as const;

export {
	LANDING_BG_COLLISION,
	LANDING_BG_INIT,
	LANDING_BG_NUMERIC,
	LANDING_BG_PHYSICS,
	LANDING_BG_RING_MIN_SPEED,
	LANDING_BG_RING_SIZE,
	LANDING_BG_RING_SPEED_SCALE,
};
