const MeetingValidationRule = {
	MEETING_ID_MAXIMUM_NUMBER: 2_147_483_647,
	MEETING_TITLE_MAXIMUM_LENGTH: 25,
	MINIMAL_HOST_LENGTH: 1,
	MINIMAL_MEETING_ID_LENGTH: 1,
	SEARCH_MINIMUM_LENGTH: 1,
} as const;

export { MeetingValidationRule };
