const UserValidationRule = {
	EMAIL_MINIMUM_LENGTH: 1,
	FIRST_NAME_MAXIMUM_LENGTH: 50,
	FIRST_NAME_MINIMUM_LENGTH: 1,
	LAST_NAME_MAXIMUM_LENGTH: 50,
	LAST_NAME_MINIMUM_LENGTH: 1,
	NAME_VALIDATION_REGEX: /^[a-zA-Z]+(?:[ -][a-zA-Z]+)*$/,
	PASSWORD_MAXIMUM_LENGTH: 64,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
